-- Fix the marital status and create the admin profile correctly
INSERT INTO public.employee_profiles (
  user_id,
  created_by,
  name_full,
  national_id,
  employee_id,
  contact_address,
  mobile_phones,
  designation,
  place_of_work,
  terms_of_service,
  nationality,
  place_of_birth,
  date_of_birth,
  date_of_appointment,
  marital_status,
  father_name,
  father_place_of_birth,
  father_nationality,
  mother_name,
  mother_place_of_birth,
  mother_nationality,
  religion,
  declaration_text,
  declaration_signed_by,
  declaration_signed_at,
  user_role,
  status,
  children,
  education,
  next_of_kin,
  projects,
  tin_no,
  spouse_name,
  spouse_contacts,
  passport_photo_url
) VALUES (
  '563912e0-871e-4dcd-9525-47a3985848a8',
  '563912e0-871e-4dcd-9525-47a3985848a8',
  'Charles Mwangomale',
  'N/A',
  'EMP001',
  'Unknown',
  ARRAY[]::text[],
  'IT Technician',
  'NAFGEM',
  'contract',
  'Unknown',
  'Unknown',
  CURRENT_DATE,
  CURRENT_DATE,
  'Single',
  'Unknown',
  'Unknown',
  'Unknown',
  'Unknown',
  'Unknown',
  'Unknown',
  'Unknown',
  'I hereby declare that the information provided above is true and correct to the best of my knowledge and belief.',
  'Charles Mwangomale',
  CURRENT_DATE,
  'admin',
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  null,
  null,
  null,
  null
) ON CONFLICT (user_id) DO NOTHING;